BOUNDARY_POINT_TABLE = "puntolindero"
BOUNDARY_TABLE = "lindero"
CONTROL_POINT_TABLE = "puntocontrol"
LENGTH_FIELD_BOUNDARY_TABLE = "longitud"
SURVEY_POINT_TABLE = "puntolevantamiento"
TERRAIN_TABLE = "terreno"
VIDA_UTIL_FIELD_BOUNDARY_TABLE = "comienzo_vida_util_version"
