["LADM_COL_V1_1.LADM_Nucleo.ueJerarquia.uej2"]
hidden="True"

["LADM_COL_V1_1.LADM_Nucleo.puntoReferencia.ue"]
hidden="True"

["LADM_COL_V1_1.LADM_Nucleo.LA_UnidadEspacial.Punto_Referencia"]
hidden="True"

["LADM_COL_V1_1.LADM_Nucleo.LA_UnidadEspacial.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V1_1.LADM_Nucleo.ExtUnidadEdificacionFisica.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V1_1.LADM_Nucleo.ExtInteresado.Ext_Direccion_ID"]
hidden="True"
