["LADM_COL_V3_0.LADM_Nucleo.col_puntoReferencia.ue"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadEspacial.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtUnidadEdificacionFisica.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtInteresado.Ext_Direccion_ID"]
hidden="True"
