DEFAULT_EPSG = "3116"
DEFAULT_TOO_LONG_BOUNDARY_SEGMENTS_TOLERANCE = 200 # meters
ERROR_LAYER_GROUP = "Validation errors"
PLUGIN_NAME = "Asistente LADM_COL"
PROJECT_GENERATOR_MIN_REQUIRED_VERSION = "3.0.5"
