from .table_mapping_config import (BOUNDARY_POINT_TABLE,
                                   SURVEY_POINT_TABLE,
                                   CONTROL_POINT_TABLE,
                                   BOUNDARY_TABLE,
                                   PLOT_TABLE,
                                   BUILDING_TABLE,
                                   BUILDING_UNIT_TABLE,
                                   COL_PARTY_TABLE,
                                   PARCEL_TABLE,
                                   RIGHT_TABLE,
                                   RESTRICTION_TABLE,
                                   RESPONSIBILITY_TABLE,
                                   ADMINISTRATIVE_SOURCE_TABLE)

LOGIC_CONSISTENCY_TABLES = {
    # Geometric tables
    BOUNDARY_POINT_TABLE: ['acuerdo',
                           'definicion_punto',
                           'descripcion_punto',
                           'exactitud_vertical',
                           'exactitud_horizontal',
                           'confiabilidad',
                           'nombre_punto',
                           'posicion_interpolacion',
                           'monumentacion',
                           'puntotipo',
                           'localizacion_original'],
    SURVEY_POINT_TABLE: ['tipo_punto_levantamiento',
                         'definicion_punto',
                         'exactitud_vertical',
                         'exactitud_horizontal',
                         'nombre_punto',
                         'posicion_interpolacion',
                         'monumentacion',
                         'puntotipo',
                         'localizacion_original'],
    CONTROL_POINT_TABLE: ['nombre_punto',
                          'exactitud_vertical',
                          'exactitud_horizontal',
                          'tipo_punto_control',
                          'confiabilidad',
                          'posicion_interpolacion',
                          'monumentacion',
                          'puntotipo',
                          'localizacion_original'],
    BOUNDARY_TABLE: ['longitud',
                     'localizacion_textual',
                     'geometria'],
    PLOT_TABLE: ['area_registral',
                 'area_calculada',
                 'avaluo_terreno',
                 'dimension',
                 'etiqueta',
                 'relacion_superficie',
                 'nivel',
                 'punto_referencia',
                 'poligono_creado'],
    BUILDING_TABLE: ['avaluo_construccion',
                     'area_construccion',
                     'tipo',
                     'dimension',
                     'etiqueta',
                     'relacion_superficie',
                     'nivel',
                     'punto_referencia',
                     'poligono_creado'],
    BUILDING_UNIT_TABLE: ['avaluo_unidad_construccion',
                          'numero_pisos',
                          'area_construida',
                          'area_privada_construida',
                          'construccion',
                          'tipo',
                          'dimension',
                          'etiqueta',
                          'relacion_superficie',
                          'nivel',
                          'punto_referencia',
                          'poligono_creado'],
    # Alphanumeric tables
    COL_PARTY_TABLE: ['documento_identidad',
                      'tipo_documento',
                      'organo_emisor',
                      'fecha_emision',
                      'primer_apellido',
                      'primer_nombre',
                      'segundo_apellido',
                      'segundo_nombre',
                      'razon_social',
                      'genero',
                      'tipo_interesado_juridico',
                      'nombre',
                      'tipo'],
    PARCEL_TABLE: ['departamento',
                   'municipio',
                   'zona',
                   'nupre',
                   'fmi',
                   'numero_predial',
                   'numero_predial_anterior',
                   'avaluo_predio',
                   'copropiedad',
                   'nombre',
                   'tipo'],
    RIGHT_TABLE: ['tipo',
                  'codigo_registral_derecho',
                  'descripcion',
                  'comprobacion_comparte',
                  'uso_efectivo',
                  'r_espacio_de_nombres',
                  'interesado_la_agrupacion_interesados',
                  'interesado_col_interesado',
                  'unidad_la_baunit',
                  'unidad_predio'],
    RESTRICTION_TABLE: ['interesado_requerido',
                        'tipo',
                        'codigo_registral_restriccion',
                        'descripcion',
                        'comprobacion_comparte',
                        'uso_efectivo',
                        'interesado_la_agrupacion_interesados',
                        'interesado_col_interesado',
                        'unidad_la_baunit',
                        'unidad_predio'],
    RESPONSIBILITY_TABLE: ['tipo',
                           'codigo_registral_responsabilidad',
                           'descripcion',
                           'comprobacion_comparte',
                           'uso_efectivo',
                           'interesado_la_agrupacion_interesados',
                           'interesado_col_interesado',
                           'unidad_la_baunit',
                           'unidad_predio'],
    ADMINISTRATIVE_SOURCE_TABLE: ['texto',
                                  'tipo',
                                  'codigo_registral_transaccion',
                                  'nombre',
                                  'fecha_aceptacion',
                                  'estado_disponibilidad',
                                  'sello_inicio_validez',
                                  'tipo_principal',
                                  'fecha_grabacion',
                                  'fecha_entrega',
                                  'oficialidad']
}
