TEST_SCHEMAS_MAPPING = {
    'test_ladm_col': 'ladm_col_v2.9.6.backup',
    'test_ladm_col_empty': 'test_ladm_col_empty_v2.9.6.backup',
    'test_ladm_validations_topology_tables': 'test_ladm_validations_topology_tables_v2.9.6.backup',
    'test_ladm_col_logic_checks': 'ladm_col_v2.9.6_logic_checks.backup',
    'test_ladm_col_queries': 'ladm_col_v2.9.6_queries.backup',
    'test_change_detections': 'test_change_detections_v2.9.6.backup',
    'test_distinct_geoms': 'test_distinct_geoms_v2.9.6.backup',
    'test_ladm_operation_model': 'test_ladm_operation_model_v2.9.6.backup',
    'test_ladm_valuation_model': 'test_ladm_valuation_model_v2.9.6.backup',
    'test_ladm_cadastral_form_model': 'test_ladm_cadastral_form_model_v2.9.6.backup',
    'test_ladm_snr_data': 'test_ladm_snr_data_v2.9.6.backup',
    'test_ladm_cadastral_manager_data': 'test_ladm_cadastral_manager_data_v2.9.6.backup',
    'test_ladm_integration': 'test_ladm_integration_v2.9.6.backup',
    'test_ladm_reference_cartography': 'test_ladm_reference_cartography_v2.9.6.backup',
    'test_ladm_ant': 'test_ladm_ant_v2.9.6.backup',
    'test_ladm_all_models': 'test_ladm_all_models_v2.9.6.backup',
    'interlis_no_ladm': 'interlis_no_ladm.backup',
    'empty_no_interlis_no_ladm': 'empty_no_interlis_no_ladm.backup',
    'interlis_ili2db3_ladm': 'interlis_ili2db3_ladm_col_221.backup',
    'ladm_col_210': 'ladm_col_operation_v_210.backup',
    'test_import_data':'test_import_data_ladm_v2.9.6.backup',
    'test_export_data':'test_export_data_ladm_v2.9.6.backup',
    'test_export_data_qpkg':'test_export_data.gpkg',
    'test_empty_ladm_gpkg': 'test_empty_ladm_v2_9_6.gpkg',
    'test_ladm_operation_model_gpkg': 'test_ladm_operation_model_v2_9_6.gpkg',
    'test_ladm_valuation_model_gpkg': 'test_ladm_valuation_model_v2_9_6.gpkg',
    'test_ladm_cadastral_form_model_gpkg': 'test_ladm_cadastral_form_model_v2_9_6.gpkg',
    'test_ladm_snr_gpkg': 'test_ladm_snr_model_v2_9_6.gpkg',
    'test_ladm_cadastral_manager_data_gpkg': 'test_ladm_cadastral_manager_model_v2_9_6.gpkg',
    'test_ladm_integration_gpkg': 'test_ladm_integration_model_v2_9_6.gpkg',
    'test_ladm_reference_cartography_gpkg': 'test_ladm_reference_cartography_model_v2_9_6.gpkg',
    'test_ladm_col_queries_qpkg': 'test_ladm_col_queries_v2_9_6.gpkg',
    'test_ladm_ant_gpkg': 'test_ladm_ant_model_v2_9_6.gpkg',
    'test_ladm_all_models_gpkg': 'test_ladm_all_models_v2_9_6.gpkg',
    'tests_data_gpkg': 'tests_data.gpkg',
    'topology_cases_gpkg': 'topology_cases.gpkg',
    'adjust_boundaries_cases_gpkg': 'adjust_boundaries_cases.gpkg',
    'no_interlis_gpkg': 'no_interlis.gpkg',
    'interlis_no_ladm_col_models_gpkg': 'interlis_no_ladm_col_models.gpkg'
}
